
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <header className="shadow-2xl p-1 ">
          <div className=" w-[1220px] mx-auto items-center flex justify-between">
            <Link href={"/"} >
              <img className="w-50" src="/logo2.png" alt="" />
            </Link>
            <div className="space-x-2">
              <Link className="bg-green-500  py-2 px-4 rounded-xl text-white  font-semibold hover:bg-green-600  " href={"/foods"}>Foods</Link>
              <Link className="bg-green-500 py-2 px-4 rounded-xl text-white font-semibold hover:bg-green-600  " href={"/reviews"}>Reviwes</Link>
            </div>
        </div>
        
       </header>


        <main className=""> {children}</main>

      </body>
    </html>
  );
}

